<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="TYSS-Manoj" failures="0" tests="1" name="Sync.AY002_Verify_User_Is_Able_To_Sync_Data_To_Cloud_In_Menu_Section_And_Cancel_The_Sync" time="150.275" errors="0" timestamp="2023-08-22T17:56:37 IST" skipped="0">
  <testcase classname="Sync.AY002_Verify_User_Is_Able_To_Sync_Data_To_Cloud_In_Menu_Section_And_Cancel_The_Sync" name="enterInvalidUsernameAndValidPassword" time="150.275"/>
  <system-out/>
</testsuite> <!-- Sync.AY002_Verify_User_Is_Able_To_Sync_Data_To_Cloud_In_Menu_Section_And_Cancel_The_Sync -->
